// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package transcode

import (
	"context"

	"github.com/st-ember/streaming-api/internal/application/ports/transcode"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTranscoder creates a new instance of MockTranscoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTranscoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTranscoder {
	mock := &MockTranscoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTranscoder is an autogenerated mock type for the Transcoder type
type MockTranscoder struct {
	mock.Mock
}

type MockTranscoder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTranscoder) EXPECT() *MockTranscoder_Expecter {
	return &MockTranscoder_Expecter{mock: &_m.Mock}
}

// Transcode provides a mock function for the type MockTranscoder
func (_mock *MockTranscoder) Transcode(ctx context.Context, resourceID string, sourceFilename string) (*transcode.TranscodeOutput, error) {
	ret := _mock.Called(ctx, resourceID, sourceFilename)

	if len(ret) == 0 {
		panic("no return value specified for Transcode")
	}

	var r0 *transcode.TranscodeOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*transcode.TranscodeOutput, error)); ok {
		return returnFunc(ctx, resourceID, sourceFilename)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *transcode.TranscodeOutput); ok {
		r0 = returnFunc(ctx, resourceID, sourceFilename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transcode.TranscodeOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, resourceID, sourceFilename)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTranscoder_Transcode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transcode'
type MockTranscoder_Transcode_Call struct {
	*mock.Call
}

// Transcode is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceID string
//   - sourceFilename string
func (_e *MockTranscoder_Expecter) Transcode(ctx interface{}, resourceID interface{}, sourceFilename interface{}) *MockTranscoder_Transcode_Call {
	return &MockTranscoder_Transcode_Call{Call: _e.mock.On("Transcode", ctx, resourceID, sourceFilename)}
}

func (_c *MockTranscoder_Transcode_Call) Run(run func(ctx context.Context, resourceID string, sourceFilename string)) *MockTranscoder_Transcode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTranscoder_Transcode_Call) Return(transcodeOutput *transcode.TranscodeOutput, err error) *MockTranscoder_Transcode_Call {
	_c.Call.Return(transcodeOutput, err)
	return _c
}

func (_c *MockTranscoder_Transcode_Call) RunAndReturn(run func(ctx context.Context, resourceID string, sourceFilename string) (*transcode.TranscodeOutput, error)) *MockTranscoder_Transcode_Call {
	_c.Call.Return(run)
	return _c
}
