// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package progressapp

import (
	"context"

	"github.com/st-ember/streaming-api/internal/domain/progress"
	mock "github.com/stretchr/testify/mock"
)

// NewMockVideoProgressUsecase creates a new instance of MockVideoProgressUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVideoProgressUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVideoProgressUsecase {
	mock := &MockVideoProgressUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVideoProgressUsecase is an autogenerated mock type for the VideoProgressUsecase type
type MockVideoProgressUsecase struct {
	mock.Mock
}

type MockVideoProgressUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVideoProgressUsecase) EXPECT() *MockVideoProgressUsecase_Expecter {
	return &MockVideoProgressUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockVideoProgressUsecase
func (_mock *MockVideoProgressUsecase) Execute(ctx context.Context, id string) (<-chan *progress.Progress, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 <-chan *progress.Progress
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (<-chan *progress.Progress, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) <-chan *progress.Progress); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *progress.Progress)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVideoProgressUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockVideoProgressUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockVideoProgressUsecase_Expecter) Execute(ctx interface{}, id interface{}) *MockVideoProgressUsecase_Execute_Call {
	return &MockVideoProgressUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, id)}
}

func (_c *MockVideoProgressUsecase_Execute_Call) Run(run func(ctx context.Context, id string)) *MockVideoProgressUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVideoProgressUsecase_Execute_Call) Return(progressCh <-chan *progress.Progress, err error) *MockVideoProgressUsecase_Execute_Call {
	_c.Call.Return(progressCh, err)
	return _c
}

func (_c *MockVideoProgressUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, id string) (<-chan *progress.Progress, error)) *MockVideoProgressUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
