// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package token

import (
	"github.com/st-ember/streaming-api/internal/application/ports/token"
	mock "github.com/stretchr/testify/mock"
)

// NewMockToken creates a new instance of MockToken. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockToken(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockToken {
	mock := &MockToken{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockToken is an autogenerated mock type for the Token type
type MockToken struct {
	mock.Mock
}

type MockToken_Expecter struct {
	mock *mock.Mock
}

func (_m *MockToken) EXPECT() *MockToken_Expecter {
	return &MockToken_Expecter{mock: &_m.Mock}
}

// GenerateAccess provides a mock function for the type MockToken
func (_mock *MockToken) GenerateAccess(userID string, username string, permissions []string) (string, error) {
	ret := _mock.Called(userID, username, permissions)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccess")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, []string) (string, error)); ok {
		return returnFunc(userID, username, permissions)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, []string) string); ok {
		r0 = returnFunc(userID, username, permissions)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, []string) error); ok {
		r1 = returnFunc(userID, username, permissions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToken_GenerateAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccess'
type MockToken_GenerateAccess_Call struct {
	*mock.Call
}

// GenerateAccess is a helper method to define mock.On call
//   - userID string
//   - username string
//   - permissions []string
func (_e *MockToken_Expecter) GenerateAccess(userID interface{}, username interface{}, permissions interface{}) *MockToken_GenerateAccess_Call {
	return &MockToken_GenerateAccess_Call{Call: _e.mock.On("GenerateAccess", userID, username, permissions)}
}

func (_c *MockToken_GenerateAccess_Call) Run(run func(userID string, username string, permissions []string)) *MockToken_GenerateAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockToken_GenerateAccess_Call) Return(s string, err error) *MockToken_GenerateAccess_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockToken_GenerateAccess_Call) RunAndReturn(run func(userID string, username string, permissions []string) (string, error)) *MockToken_GenerateAccess_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRefresh provides a mock function for the type MockToken
func (_mock *MockToken) GenerateRefresh(userID string) (string, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRefresh")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToken_GenerateRefresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRefresh'
type MockToken_GenerateRefresh_Call struct {
	*mock.Call
}

// GenerateRefresh is a helper method to define mock.On call
//   - userID string
func (_e *MockToken_Expecter) GenerateRefresh(userID interface{}) *MockToken_GenerateRefresh_Call {
	return &MockToken_GenerateRefresh_Call{Call: _e.mock.On("GenerateRefresh", userID)}
}

func (_c *MockToken_GenerateRefresh_Call) Run(run func(userID string)) *MockToken_GenerateRefresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockToken_GenerateRefresh_Call) Return(s string, err error) *MockToken_GenerateRefresh_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockToken_GenerateRefresh_Call) RunAndReturn(run func(userID string) (string, error)) *MockToken_GenerateRefresh_Call {
	_c.Call.Return(run)
	return _c
}

// ParseAccess provides a mock function for the type MockToken
func (_mock *MockToken) ParseAccess(token1 string) (*token.AccessClaims, error) {
	ret := _mock.Called(token1)

	if len(ret) == 0 {
		panic("no return value specified for ParseAccess")
	}

	var r0 *token.AccessClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*token.AccessClaims, error)); ok {
		return returnFunc(token1)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *token.AccessClaims); ok {
		r0 = returnFunc(token1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token.AccessClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToken_ParseAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseAccess'
type MockToken_ParseAccess_Call struct {
	*mock.Call
}

// ParseAccess is a helper method to define mock.On call
//   - token1 string
func (_e *MockToken_Expecter) ParseAccess(token1 interface{}) *MockToken_ParseAccess_Call {
	return &MockToken_ParseAccess_Call{Call: _e.mock.On("ParseAccess", token1)}
}

func (_c *MockToken_ParseAccess_Call) Run(run func(token1 string)) *MockToken_ParseAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockToken_ParseAccess_Call) Return(accessClaims *token.AccessClaims, err error) *MockToken_ParseAccess_Call {
	_c.Call.Return(accessClaims, err)
	return _c
}

func (_c *MockToken_ParseAccess_Call) RunAndReturn(run func(token1 string) (*token.AccessClaims, error)) *MockToken_ParseAccess_Call {
	_c.Call.Return(run)
	return _c
}

// ParseRefresh provides a mock function for the type MockToken
func (_mock *MockToken) ParseRefresh(token1 string) (*token.RefreshClaims, error) {
	ret := _mock.Called(token1)

	if len(ret) == 0 {
		panic("no return value specified for ParseRefresh")
	}

	var r0 *token.RefreshClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*token.RefreshClaims, error)); ok {
		return returnFunc(token1)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *token.RefreshClaims); ok {
		r0 = returnFunc(token1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token.RefreshClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToken_ParseRefresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseRefresh'
type MockToken_ParseRefresh_Call struct {
	*mock.Call
}

// ParseRefresh is a helper method to define mock.On call
//   - token1 string
func (_e *MockToken_Expecter) ParseRefresh(token1 interface{}) *MockToken_ParseRefresh_Call {
	return &MockToken_ParseRefresh_Call{Call: _e.mock.On("ParseRefresh", token1)}
}

func (_c *MockToken_ParseRefresh_Call) Run(run func(token1 string)) *MockToken_ParseRefresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockToken_ParseRefresh_Call) Return(refreshClaims *token.RefreshClaims, err error) *MockToken_ParseRefresh_Call {
	_c.Call.Return(refreshClaims, err)
	return _c
}

func (_c *MockToken_ParseRefresh_Call) RunAndReturn(run func(token1 string) (*token.RefreshClaims, error)) *MockToken_ParseRefresh_Call {
	_c.Call.Return(run)
	return _c
}
