// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jobapp

import (
	"context"
	"time"

	"github.com/st-ember/streaming-api/internal/domain/job"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCompleteTranscodeJobUsecase creates a new instance of MockCompleteTranscodeJobUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCompleteTranscodeJobUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCompleteTranscodeJobUsecase {
	mock := &MockCompleteTranscodeJobUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCompleteTranscodeJobUsecase is an autogenerated mock type for the CompleteTranscodeJobUsecase type
type MockCompleteTranscodeJobUsecase struct {
	mock.Mock
}

type MockCompleteTranscodeJobUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCompleteTranscodeJobUsecase) EXPECT() *MockCompleteTranscodeJobUsecase_Expecter {
	return &MockCompleteTranscodeJobUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockCompleteTranscodeJobUsecase
func (_mock *MockCompleteTranscodeJobUsecase) Execute(ctx context.Context, job1 *job.Job, result string, duration time.Duration) error {
	ret := _mock.Called(ctx, job1, result, duration)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *job.Job, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, job1, result, duration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCompleteTranscodeJobUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCompleteTranscodeJobUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - job1 *job.Job
//   - result string
//   - duration time.Duration
func (_e *MockCompleteTranscodeJobUsecase_Expecter) Execute(ctx interface{}, job1 interface{}, result interface{}, duration interface{}) *MockCompleteTranscodeJobUsecase_Execute_Call {
	return &MockCompleteTranscodeJobUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, job1, result, duration)}
}

func (_c *MockCompleteTranscodeJobUsecase_Execute_Call) Run(run func(ctx context.Context, job1 *job.Job, result string, duration time.Duration)) *MockCompleteTranscodeJobUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *job.Job
		if args[1] != nil {
			arg1 = args[1].(*job.Job)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCompleteTranscodeJobUsecase_Execute_Call) Return(err error) *MockCompleteTranscodeJobUsecase_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCompleteTranscodeJobUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, job1 *job.Job, result string, duration time.Duration) error) *MockCompleteTranscodeJobUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
