// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jobapp

import (
	"context"

	"github.com/st-ember/streaming-api/internal/domain/job"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFailTranscodeJobUsecase creates a new instance of MockFailTranscodeJobUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFailTranscodeJobUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFailTranscodeJobUsecase {
	mock := &MockFailTranscodeJobUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFailTranscodeJobUsecase is an autogenerated mock type for the FailTranscodeJobUsecase type
type MockFailTranscodeJobUsecase struct {
	mock.Mock
}

type MockFailTranscodeJobUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFailTranscodeJobUsecase) EXPECT() *MockFailTranscodeJobUsecase_Expecter {
	return &MockFailTranscodeJobUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockFailTranscodeJobUsecase
func (_mock *MockFailTranscodeJobUsecase) Execute(ctx context.Context, job1 *job.Job, errMsg string) error {
	ret := _mock.Called(ctx, job1, errMsg)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *job.Job, string) error); ok {
		r0 = returnFunc(ctx, job1, errMsg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFailTranscodeJobUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockFailTranscodeJobUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - job1 *job.Job
//   - errMsg string
func (_e *MockFailTranscodeJobUsecase_Expecter) Execute(ctx interface{}, job1 interface{}, errMsg interface{}) *MockFailTranscodeJobUsecase_Execute_Call {
	return &MockFailTranscodeJobUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, job1, errMsg)}
}

func (_c *MockFailTranscodeJobUsecase_Execute_Call) Run(run func(ctx context.Context, job1 *job.Job, errMsg string)) *MockFailTranscodeJobUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *job.Job
		if args[1] != nil {
			arg1 = args[1].(*job.Job)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFailTranscodeJobUsecase_Execute_Call) Return(err error) *MockFailTranscodeJobUsecase_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFailTranscodeJobUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, job1 *job.Job, errMsg string) error) *MockFailTranscodeJobUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
