// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jobapp

import (
	"context"

	"github.com/st-ember/streaming-api/internal/domain/job"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFindNextPendingTranscodeJobUsecase creates a new instance of MockFindNextPendingTranscodeJobUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFindNextPendingTranscodeJobUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFindNextPendingTranscodeJobUsecase {
	mock := &MockFindNextPendingTranscodeJobUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFindNextPendingTranscodeJobUsecase is an autogenerated mock type for the FindNextPendingTranscodeJobUsecase type
type MockFindNextPendingTranscodeJobUsecase struct {
	mock.Mock
}

type MockFindNextPendingTranscodeJobUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFindNextPendingTranscodeJobUsecase) EXPECT() *MockFindNextPendingTranscodeJobUsecase_Expecter {
	return &MockFindNextPendingTranscodeJobUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockFindNextPendingTranscodeJobUsecase
func (_mock *MockFindNextPendingTranscodeJobUsecase) Execute(ctx context.Context) (*job.Job, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *job.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*job.Job, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *job.Job); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*job.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFindNextPendingTranscodeJobUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockFindNextPendingTranscodeJobUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFindNextPendingTranscodeJobUsecase_Expecter) Execute(ctx interface{}) *MockFindNextPendingTranscodeJobUsecase_Execute_Call {
	return &MockFindNextPendingTranscodeJobUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *MockFindNextPendingTranscodeJobUsecase_Execute_Call) Run(run func(ctx context.Context)) *MockFindNextPendingTranscodeJobUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFindNextPendingTranscodeJobUsecase_Execute_Call) Return(job1 *job.Job, err error) *MockFindNextPendingTranscodeJobUsecase_Execute_Call {
	_c.Call.Return(job1, err)
	return _c
}

func (_c *MockFindNextPendingTranscodeJobUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context) (*job.Job, error)) *MockFindNextPendingTranscodeJobUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
