// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jobapp

import (
	"context"

	"github.com/st-ember/streaming-api/internal/application/jobapp"
	"github.com/st-ember/streaming-api/internal/domain/job"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStartTranscodeJobUsecase creates a new instance of MockStartTranscodeJobUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStartTranscodeJobUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStartTranscodeJobUsecase {
	mock := &MockStartTranscodeJobUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStartTranscodeJobUsecase is an autogenerated mock type for the StartTranscodeJobUsecase type
type MockStartTranscodeJobUsecase struct {
	mock.Mock
}

type MockStartTranscodeJobUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStartTranscodeJobUsecase) EXPECT() *MockStartTranscodeJobUsecase_Expecter {
	return &MockStartTranscodeJobUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockStartTranscodeJobUsecase
func (_mock *MockStartTranscodeJobUsecase) Execute(ctx context.Context, job1 *job.Job) (*jobapp.StartTranscodeJobResult, error) {
	ret := _mock.Called(ctx, job1)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *jobapp.StartTranscodeJobResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *job.Job) (*jobapp.StartTranscodeJobResult, error)); ok {
		return returnFunc(ctx, job1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *job.Job) *jobapp.StartTranscodeJobResult); ok {
		r0 = returnFunc(ctx, job1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jobapp.StartTranscodeJobResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *job.Job) error); ok {
		r1 = returnFunc(ctx, job1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStartTranscodeJobUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockStartTranscodeJobUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - job1 *job.Job
func (_e *MockStartTranscodeJobUsecase_Expecter) Execute(ctx interface{}, job1 interface{}) *MockStartTranscodeJobUsecase_Execute_Call {
	return &MockStartTranscodeJobUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, job1)}
}

func (_c *MockStartTranscodeJobUsecase_Execute_Call) Run(run func(ctx context.Context, job1 *job.Job)) *MockStartTranscodeJobUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *job.Job
		if args[1] != nil {
			arg1 = args[1].(*job.Job)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStartTranscodeJobUsecase_Execute_Call) Return(startTranscodeJobResult *jobapp.StartTranscodeJobResult, err error) *MockStartTranscodeJobUsecase_Execute_Call {
	_c.Call.Return(startTranscodeJobResult, err)
	return _c
}

func (_c *MockStartTranscodeJobUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, job1 *job.Job) (*jobapp.StartTranscodeJobResult, error)) *MockStartTranscodeJobUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
