// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package progressstream

import (
	"context"

	"github.com/st-ember/streaming-api/internal/domain/progress"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProgressStreamer creates a new instance of MockProgressStreamer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProgressStreamer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProgressStreamer {
	mock := &MockProgressStreamer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProgressStreamer is an autogenerated mock type for the ProgressStreamer type
type MockProgressStreamer struct {
	mock.Mock
}

type MockProgressStreamer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProgressStreamer) EXPECT() *MockProgressStreamer_Expecter {
	return &MockProgressStreamer_Expecter{mock: &_m.Mock}
}

// Push provides a mock function for the type MockProgressStreamer
func (_mock *MockProgressStreamer) Push(ctx context.Context, jobID string, prg *progress.Progress) error {
	ret := _mock.Called(ctx, jobID, prg)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *progress.Progress) error); ok {
		r0 = returnFunc(ctx, jobID, prg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProgressStreamer_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type MockProgressStreamer_Push_Call struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID string
//   - prg *progress.Progress
func (_e *MockProgressStreamer_Expecter) Push(ctx interface{}, jobID interface{}, prg interface{}) *MockProgressStreamer_Push_Call {
	return &MockProgressStreamer_Push_Call{Call: _e.mock.On("Push", ctx, jobID, prg)}
}

func (_c *MockProgressStreamer_Push_Call) Run(run func(ctx context.Context, jobID string, prg *progress.Progress)) *MockProgressStreamer_Push_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *progress.Progress
		if args[2] != nil {
			arg2 = args[2].(*progress.Progress)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProgressStreamer_Push_Call) Return(err error) *MockProgressStreamer_Push_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProgressStreamer_Push_Call) RunAndReturn(run func(ctx context.Context, jobID string, prg *progress.Progress) error) *MockProgressStreamer_Push_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type MockProgressStreamer
func (_mock *MockProgressStreamer) Read(ctx context.Context, jobID string) (<-chan *progress.Progress, error) {
	ret := _mock.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 <-chan *progress.Progress
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (<-chan *progress.Progress, error)); ok {
		return returnFunc(ctx, jobID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) <-chan *progress.Progress); ok {
		r0 = returnFunc(ctx, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *progress.Progress)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProgressStreamer_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockProgressStreamer_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID string
func (_e *MockProgressStreamer_Expecter) Read(ctx interface{}, jobID interface{}) *MockProgressStreamer_Read_Call {
	return &MockProgressStreamer_Read_Call{Call: _e.mock.On("Read", ctx, jobID)}
}

func (_c *MockProgressStreamer_Read_Call) Run(run func(ctx context.Context, jobID string)) *MockProgressStreamer_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProgressStreamer_Read_Call) Return(progressCh <-chan *progress.Progress, err error) *MockProgressStreamer_Read_Call {
	_c.Call.Return(progressCh, err)
	return _c
}

func (_c *MockProgressStreamer_Read_Call) RunAndReturn(run func(ctx context.Context, jobID string) (<-chan *progress.Progress, error)) *MockProgressStreamer_Read_Call {
	_c.Call.Return(run)
	return _c
}
