// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package exec

import (
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCmd creates a new instance of MockCmd. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCmd(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCmd {
	mock := &MockCmd{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCmd is an autogenerated mock type for the Cmd type
type MockCmd struct {
	mock.Mock
}

type MockCmd_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCmd) EXPECT() *MockCmd_Expecter {
	return &MockCmd_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockCmd
func (_mock *MockCmd) Run() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCmd_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockCmd_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *MockCmd_Expecter) Run() *MockCmd_Run_Call {
	return &MockCmd_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *MockCmd_Run_Call) Run(run func()) *MockCmd_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCmd_Run_Call) Return(err error) *MockCmd_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCmd_Run_Call) RunAndReturn(run func() error) *MockCmd_Run_Call {
	_c.Call.Return(run)
	return _c
}

// SetStderr provides a mock function for the type MockCmd
func (_mock *MockCmd) SetStderr(writer io.Writer) {
	_mock.Called(writer)
	return
}

// MockCmd_SetStderr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStderr'
type MockCmd_SetStderr_Call struct {
	*mock.Call
}

// SetStderr is a helper method to define mock.On call
//   - writer io.Writer
func (_e *MockCmd_Expecter) SetStderr(writer interface{}) *MockCmd_SetStderr_Call {
	return &MockCmd_SetStderr_Call{Call: _e.mock.On("SetStderr", writer)}
}

func (_c *MockCmd_SetStderr_Call) Run(run func(writer io.Writer)) *MockCmd_SetStderr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Writer
		if args[0] != nil {
			arg0 = args[0].(io.Writer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCmd_SetStderr_Call) Return() *MockCmd_SetStderr_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCmd_SetStderr_Call) RunAndReturn(run func(writer io.Writer)) *MockCmd_SetStderr_Call {
	_c.Run(run)
	return _c
}

// SetStdout provides a mock function for the type MockCmd
func (_mock *MockCmd) SetStdout(writer io.Writer) {
	_mock.Called(writer)
	return
}

// MockCmd_SetStdout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStdout'
type MockCmd_SetStdout_Call struct {
	*mock.Call
}

// SetStdout is a helper method to define mock.On call
//   - writer io.Writer
func (_e *MockCmd_Expecter) SetStdout(writer interface{}) *MockCmd_SetStdout_Call {
	return &MockCmd_SetStdout_Call{Call: _e.mock.On("SetStdout", writer)}
}

func (_c *MockCmd_SetStdout_Call) Run(run func(writer io.Writer)) *MockCmd_SetStdout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Writer
		if args[0] != nil {
			arg0 = args[0].(io.Writer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCmd_SetStdout_Call) Return() *MockCmd_SetStdout_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCmd_SetStdout_Call) RunAndReturn(run func(writer io.Writer)) *MockCmd_SetStdout_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type MockCmd
func (_mock *MockCmd) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCmd_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockCmd_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockCmd_Expecter) Start() *MockCmd_Start_Call {
	return &MockCmd_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockCmd_Start_Call) Run(run func()) *MockCmd_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCmd_Start_Call) Return(err error) *MockCmd_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCmd_Start_Call) RunAndReturn(run func() error) *MockCmd_Start_Call {
	_c.Call.Return(run)
	return _c
}

// StderrPipe provides a mock function for the type MockCmd
func (_mock *MockCmd) StderrPipe() (io.ReadCloser, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StderrPipe")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (io.ReadCloser, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() io.ReadCloser); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCmd_StderrPipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StderrPipe'
type MockCmd_StderrPipe_Call struct {
	*mock.Call
}

// StderrPipe is a helper method to define mock.On call
func (_e *MockCmd_Expecter) StderrPipe() *MockCmd_StderrPipe_Call {
	return &MockCmd_StderrPipe_Call{Call: _e.mock.On("StderrPipe")}
}

func (_c *MockCmd_StderrPipe_Call) Run(run func()) *MockCmd_StderrPipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCmd_StderrPipe_Call) Return(readCloser io.ReadCloser, err error) *MockCmd_StderrPipe_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockCmd_StderrPipe_Call) RunAndReturn(run func() (io.ReadCloser, error)) *MockCmd_StderrPipe_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function for the type MockCmd
func (_mock *MockCmd) Wait() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCmd_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockCmd_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
func (_e *MockCmd_Expecter) Wait() *MockCmd_Wait_Call {
	return &MockCmd_Wait_Call{Call: _e.mock.On("Wait")}
}

func (_c *MockCmd_Wait_Call) Run(run func()) *MockCmd_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCmd_Wait_Call) Return(err error) *MockCmd_Wait_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCmd_Wait_Call) RunAndReturn(run func() error) *MockCmd_Wait_Call {
	_c.Call.Return(run)
	return _c
}
