// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package exec

import (
	"context"

	"github.com/st-ember/streaming-api/internal/application/ports/exec"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCommander creates a new instance of MockCommander. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommander(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommander {
	mock := &MockCommander{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommander is an autogenerated mock type for the Commander type
type MockCommander struct {
	mock.Mock
}

type MockCommander_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommander) EXPECT() *MockCommander_Expecter {
	return &MockCommander_Expecter{mock: &_m.Mock}
}

// CommandContext provides a mock function for the type MockCommander
func (_mock *MockCommander) CommandContext(ctx context.Context, name string, args ...string) exec.Cmd {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, name, args)
	} else {
		tmpRet = _mock.Called(ctx, name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CommandContext")
	}

	var r0 exec.Cmd
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) exec.Cmd); ok {
		r0 = returnFunc(ctx, name, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(exec.Cmd)
		}
	}
	return r0
}

// MockCommander_CommandContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommandContext'
type MockCommander_CommandContext_Call struct {
	*mock.Call
}

// CommandContext is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - args ...string
func (_e *MockCommander_Expecter) CommandContext(ctx interface{}, name interface{}, args ...interface{}) *MockCommander_CommandContext_Call {
	return &MockCommander_CommandContext_Call{Call: _e.mock.On("CommandContext",
		append([]interface{}{ctx, name}, args...)...)}
}

func (_c *MockCommander_CommandContext_Call) Run(run func(ctx context.Context, name string, args ...string)) *MockCommander_CommandContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCommander_CommandContext_Call) Return(cmd exec.Cmd) *MockCommander_CommandContext_Call {
	_c.Call.Return(cmd)
	return _c
}

func (_c *MockCommander_CommandContext_Call) RunAndReturn(run func(ctx context.Context, name string, args ...string) exec.Cmd) *MockCommander_CommandContext_Call {
	_c.Call.Return(run)
	return _c
}
