// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repo

import (
	"context"

	"github.com/st-ember/streaming-api/internal/domain/user"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthRepo creates a new instance of MockAuthRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthRepo {
	mock := &MockAuthRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthRepo is an autogenerated mock type for the AuthRepo type
type MockAuthRepo struct {
	mock.Mock
}

type MockAuthRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthRepo) EXPECT() *MockAuthRepo_Expecter {
	return &MockAuthRepo_Expecter{mock: &_m.Mock}
}

// FindPermissionsByRole provides a mock function for the type MockAuthRepo
func (_mock *MockAuthRepo) FindPermissionsByRole(ctx context.Context, roleName string) ([]string, error) {
	ret := _mock.Called(ctx, roleName)

	if len(ret) == 0 {
		panic("no return value specified for FindPermissionsByRole")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, roleName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, roleName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, roleName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepo_FindPermissionsByRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPermissionsByRole'
type MockAuthRepo_FindPermissionsByRole_Call struct {
	*mock.Call
}

// FindPermissionsByRole is a helper method to define mock.On call
//   - ctx context.Context
//   - roleName string
func (_e *MockAuthRepo_Expecter) FindPermissionsByRole(ctx interface{}, roleName interface{}) *MockAuthRepo_FindPermissionsByRole_Call {
	return &MockAuthRepo_FindPermissionsByRole_Call{Call: _e.mock.On("FindPermissionsByRole", ctx, roleName)}
}

func (_c *MockAuthRepo_FindPermissionsByRole_Call) Run(run func(ctx context.Context, roleName string)) *MockAuthRepo_FindPermissionsByRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepo_FindPermissionsByRole_Call) Return(strings []string, err error) *MockAuthRepo_FindPermissionsByRole_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockAuthRepo_FindPermissionsByRole_Call) RunAndReturn(run func(ctx context.Context, roleName string) ([]string, error)) *MockAuthRepo_FindPermissionsByRole_Call {
	_c.Call.Return(run)
	return _c
}

// FindPermissionsByUserID provides a mock function for the type MockAuthRepo
func (_mock *MockAuthRepo) FindPermissionsByUserID(ctx context.Context, userID string) ([]string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindPermissionsByUserID")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepo_FindPermissionsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPermissionsByUserID'
type MockAuthRepo_FindPermissionsByUserID_Call struct {
	*mock.Call
}

// FindPermissionsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAuthRepo_Expecter) FindPermissionsByUserID(ctx interface{}, userID interface{}) *MockAuthRepo_FindPermissionsByUserID_Call {
	return &MockAuthRepo_FindPermissionsByUserID_Call{Call: _e.mock.On("FindPermissionsByUserID", ctx, userID)}
}

func (_c *MockAuthRepo_FindPermissionsByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockAuthRepo_FindPermissionsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepo_FindPermissionsByUserID_Call) Return(strings []string, err error) *MockAuthRepo_FindPermissionsByUserID_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockAuthRepo_FindPermissionsByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]string, error)) *MockAuthRepo_FindPermissionsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByKey provides a mock function for the type MockAuthRepo
func (_mock *MockAuthRepo) FindUserByKey(ctx context.Context, login string) (*user.User, error) {
	ret := _mock.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByKey")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return returnFunc(ctx, login)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = returnFunc(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, login)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepo_FindUserByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByKey'
type MockAuthRepo_FindUserByKey_Call struct {
	*mock.Call
}

// FindUserByKey is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *MockAuthRepo_Expecter) FindUserByKey(ctx interface{}, login interface{}) *MockAuthRepo_FindUserByKey_Call {
	return &MockAuthRepo_FindUserByKey_Call{Call: _e.mock.On("FindUserByKey", ctx, login)}
}

func (_c *MockAuthRepo_FindUserByKey_Call) Run(run func(ctx context.Context, login string)) *MockAuthRepo_FindUserByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepo_FindUserByKey_Call) Return(user1 *user.User, err error) *MockAuthRepo_FindUserByKey_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockAuthRepo_FindUserByKey_Call) RunAndReturn(run func(ctx context.Context, login string) (*user.User, error)) *MockAuthRepo_FindUserByKey_Call {
	_c.Call.Return(run)
	return _c
}

// SaveUser provides a mock function for the type MockAuthRepo
func (_mock *MockAuthRepo) SaveUser(ctx context.Context, u *user.User) error {
	ret := _mock.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.User) error); ok {
		r0 = returnFunc(ctx, u)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthRepo_SaveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveUser'
type MockAuthRepo_SaveUser_Call struct {
	*mock.Call
}

// SaveUser is a helper method to define mock.On call
//   - ctx context.Context
//   - u *user.User
func (_e *MockAuthRepo_Expecter) SaveUser(ctx interface{}, u interface{}) *MockAuthRepo_SaveUser_Call {
	return &MockAuthRepo_SaveUser_Call{Call: _e.mock.On("SaveUser", ctx, u)}
}

func (_c *MockAuthRepo_SaveUser_Call) Run(run func(ctx context.Context, u *user.User)) *MockAuthRepo_SaveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *user.User
		if args[1] != nil {
			arg1 = args[1].(*user.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepo_SaveUser_Call) Return(err error) *MockAuthRepo_SaveUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthRepo_SaveUser_Call) RunAndReturn(run func(ctx context.Context, u *user.User) error) *MockAuthRepo_SaveUser_Call {
	_c.Call.Return(run)
	return _c
}

// SaveUserRole provides a mock function for the type MockAuthRepo
func (_mock *MockAuthRepo) SaveUserRole(ctx context.Context, userID string, roleName string) error {
	ret := _mock.Called(ctx, userID, roleName)

	if len(ret) == 0 {
		panic("no return value specified for SaveUserRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, roleName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthRepo_SaveUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveUserRole'
type MockAuthRepo_SaveUserRole_Call struct {
	*mock.Call
}

// SaveUserRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - roleName string
func (_e *MockAuthRepo_Expecter) SaveUserRole(ctx interface{}, userID interface{}, roleName interface{}) *MockAuthRepo_SaveUserRole_Call {
	return &MockAuthRepo_SaveUserRole_Call{Call: _e.mock.On("SaveUserRole", ctx, userID, roleName)}
}

func (_c *MockAuthRepo_SaveUserRole_Call) Run(run func(ctx context.Context, userID string, roleName string)) *MockAuthRepo_SaveUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthRepo_SaveUserRole_Call) Return(err error) *MockAuthRepo_SaveUserRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthRepo_SaveUserRole_Call) RunAndReturn(run func(ctx context.Context, userID string, roleName string) error) *MockAuthRepo_SaveUserRole_Call {
	_c.Call.Return(run)
	return _c
}

// SyncPermissions provides a mock function for the type MockAuthRepo
func (_mock *MockAuthRepo) SyncPermissions(ctx context.Context, permissions []string) error {
	ret := _mock.Called(ctx, permissions)

	if len(ret) == 0 {
		panic("no return value specified for SyncPermissions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, permissions)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthRepo_SyncPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncPermissions'
type MockAuthRepo_SyncPermissions_Call struct {
	*mock.Call
}

// SyncPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - permissions []string
func (_e *MockAuthRepo_Expecter) SyncPermissions(ctx interface{}, permissions interface{}) *MockAuthRepo_SyncPermissions_Call {
	return &MockAuthRepo_SyncPermissions_Call{Call: _e.mock.On("SyncPermissions", ctx, permissions)}
}

func (_c *MockAuthRepo_SyncPermissions_Call) Run(run func(ctx context.Context, permissions []string)) *MockAuthRepo_SyncPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepo_SyncPermissions_Call) Return(err error) *MockAuthRepo_SyncPermissions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthRepo_SyncPermissions_Call) RunAndReturn(run func(ctx context.Context, permissions []string) error) *MockAuthRepo_SyncPermissions_Call {
	_c.Call.Return(run)
	return _c
}
