// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repo

import (
	"context"

	"github.com/st-ember/streaming-api/internal/domain/job"
	mock "github.com/stretchr/testify/mock"
)

// NewMockJobRepo creates a new instance of MockJobRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobRepo {
	mock := &MockJobRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobRepo is an autogenerated mock type for the JobRepo type
type MockJobRepo struct {
	mock.Mock
}

type MockJobRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobRepo) EXPECT() *MockJobRepo_Expecter {
	return &MockJobRepo_Expecter{mock: &_m.Mock}
}

// FindByVideoID provides a mock function for the type MockJobRepo
func (_mock *MockJobRepo) FindByVideoID(ctx context.Context, id string) (*job.Job, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByVideoID")
	}

	var r0 *job.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*job.Job, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *job.Job); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*job.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobRepo_FindByVideoID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByVideoID'
type MockJobRepo_FindByVideoID_Call struct {
	*mock.Call
}

// FindByVideoID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockJobRepo_Expecter) FindByVideoID(ctx interface{}, id interface{}) *MockJobRepo_FindByVideoID_Call {
	return &MockJobRepo_FindByVideoID_Call{Call: _e.mock.On("FindByVideoID", ctx, id)}
}

func (_c *MockJobRepo_FindByVideoID_Call) Run(run func(ctx context.Context, id string)) *MockJobRepo_FindByVideoID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobRepo_FindByVideoID_Call) Return(job1 *job.Job, err error) *MockJobRepo_FindByVideoID_Call {
	_c.Call.Return(job1, err)
	return _c
}

func (_c *MockJobRepo_FindByVideoID_Call) RunAndReturn(run func(ctx context.Context, id string) (*job.Job, error)) *MockJobRepo_FindByVideoID_Call {
	_c.Call.Return(run)
	return _c
}

// FindNextPendingTranscodeJob provides a mock function for the type MockJobRepo
func (_mock *MockJobRepo) FindNextPendingTranscodeJob(ctx context.Context) (*job.Job, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindNextPendingTranscodeJob")
	}

	var r0 *job.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*job.Job, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *job.Job); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*job.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobRepo_FindNextPendingTranscodeJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNextPendingTranscodeJob'
type MockJobRepo_FindNextPendingTranscodeJob_Call struct {
	*mock.Call
}

// FindNextPendingTranscodeJob is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockJobRepo_Expecter) FindNextPendingTranscodeJob(ctx interface{}) *MockJobRepo_FindNextPendingTranscodeJob_Call {
	return &MockJobRepo_FindNextPendingTranscodeJob_Call{Call: _e.mock.On("FindNextPendingTranscodeJob", ctx)}
}

func (_c *MockJobRepo_FindNextPendingTranscodeJob_Call) Run(run func(ctx context.Context)) *MockJobRepo_FindNextPendingTranscodeJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobRepo_FindNextPendingTranscodeJob_Call) Return(job1 *job.Job, err error) *MockJobRepo_FindNextPendingTranscodeJob_Call {
	_c.Call.Return(job1, err)
	return _c
}

func (_c *MockJobRepo_FindNextPendingTranscodeJob_Call) RunAndReturn(run func(ctx context.Context) (*job.Job, error)) *MockJobRepo_FindNextPendingTranscodeJob_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockJobRepo
func (_mock *MockJobRepo) Save(ctx context.Context, job1 *job.Job) error {
	ret := _mock.Called(ctx, job1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *job.Job) error); ok {
		r0 = returnFunc(ctx, job1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobRepo_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockJobRepo_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - job1 *job.Job
func (_e *MockJobRepo_Expecter) Save(ctx interface{}, job1 interface{}) *MockJobRepo_Save_Call {
	return &MockJobRepo_Save_Call{Call: _e.mock.On("Save", ctx, job1)}
}

func (_c *MockJobRepo_Save_Call) Run(run func(ctx context.Context, job1 *job.Job)) *MockJobRepo_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *job.Job
		if args[1] != nil {
			arg1 = args[1].(*job.Job)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobRepo_Save_Call) Return(err error) *MockJobRepo_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobRepo_Save_Call) RunAndReturn(run func(ctx context.Context, job1 *job.Job) error) *MockJobRepo_Save_Call {
	_c.Call.Return(run)
	return _c
}
