// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repo

import (
	"context"

	"github.com/st-ember/streaming-api/internal/application/ports/repo"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUnitOfWork creates a new instance of MockUnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnitOfWork(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnitOfWork {
	mock := &MockUnitOfWork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUnitOfWork is an autogenerated mock type for the UnitOfWork type
type MockUnitOfWork struct {
	mock.Mock
}

type MockUnitOfWork_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnitOfWork) EXPECT() *MockUnitOfWork_Expecter {
	return &MockUnitOfWork_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function for the type MockUnitOfWork
func (_mock *MockUnitOfWork) Commit(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUnitOfWork_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockUnitOfWork_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUnitOfWork_Expecter) Commit(ctx interface{}) *MockUnitOfWork_Commit_Call {
	return &MockUnitOfWork_Commit_Call{Call: _e.mock.On("Commit", ctx)}
}

func (_c *MockUnitOfWork_Commit_Call) Run(run func(ctx context.Context)) *MockUnitOfWork_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUnitOfWork_Commit_Call) Return(err error) *MockUnitOfWork_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUnitOfWork_Commit_Call) RunAndReturn(run func(ctx context.Context) error) *MockUnitOfWork_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// JobRepo provides a mock function for the type MockUnitOfWork
func (_mock *MockUnitOfWork) JobRepo() repo.JobRepo {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for JobRepo")
	}

	var r0 repo.JobRepo
	if returnFunc, ok := ret.Get(0).(func() repo.JobRepo); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repo.JobRepo)
		}
	}
	return r0
}

// MockUnitOfWork_JobRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JobRepo'
type MockUnitOfWork_JobRepo_Call struct {
	*mock.Call
}

// JobRepo is a helper method to define mock.On call
func (_e *MockUnitOfWork_Expecter) JobRepo() *MockUnitOfWork_JobRepo_Call {
	return &MockUnitOfWork_JobRepo_Call{Call: _e.mock.On("JobRepo")}
}

func (_c *MockUnitOfWork_JobRepo_Call) Run(run func()) *MockUnitOfWork_JobRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnitOfWork_JobRepo_Call) Return(jobRepo repo.JobRepo) *MockUnitOfWork_JobRepo_Call {
	_c.Call.Return(jobRepo)
	return _c
}

func (_c *MockUnitOfWork_JobRepo_Call) RunAndReturn(run func() repo.JobRepo) *MockUnitOfWork_JobRepo_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type MockUnitOfWork
func (_mock *MockUnitOfWork) Rollback(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUnitOfWork_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockUnitOfWork_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUnitOfWork_Expecter) Rollback(ctx interface{}) *MockUnitOfWork_Rollback_Call {
	return &MockUnitOfWork_Rollback_Call{Call: _e.mock.On("Rollback", ctx)}
}

func (_c *MockUnitOfWork_Rollback_Call) Run(run func(ctx context.Context)) *MockUnitOfWork_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUnitOfWork_Rollback_Call) Return(err error) *MockUnitOfWork_Rollback_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUnitOfWork_Rollback_Call) RunAndReturn(run func(ctx context.Context) error) *MockUnitOfWork_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// VideoRepo provides a mock function for the type MockUnitOfWork
func (_mock *MockUnitOfWork) VideoRepo() repo.VideoRepo {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for VideoRepo")
	}

	var r0 repo.VideoRepo
	if returnFunc, ok := ret.Get(0).(func() repo.VideoRepo); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repo.VideoRepo)
		}
	}
	return r0
}

// MockUnitOfWork_VideoRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VideoRepo'
type MockUnitOfWork_VideoRepo_Call struct {
	*mock.Call
}

// VideoRepo is a helper method to define mock.On call
func (_e *MockUnitOfWork_Expecter) VideoRepo() *MockUnitOfWork_VideoRepo_Call {
	return &MockUnitOfWork_VideoRepo_Call{Call: _e.mock.On("VideoRepo")}
}

func (_c *MockUnitOfWork_VideoRepo_Call) Run(run func()) *MockUnitOfWork_VideoRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnitOfWork_VideoRepo_Call) Return(videoRepo repo.VideoRepo) *MockUnitOfWork_VideoRepo_Call {
	_c.Call.Return(videoRepo)
	return _c
}

func (_c *MockUnitOfWork_VideoRepo_Call) RunAndReturn(run func() repo.VideoRepo) *MockUnitOfWork_VideoRepo_Call {
	_c.Call.Return(run)
	return _c
}
