// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repo

import (
	"context"

	"github.com/st-ember/streaming-api/internal/application/ports/repo"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUnitOfWorkFactory creates a new instance of MockUnitOfWorkFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnitOfWorkFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnitOfWorkFactory {
	mock := &MockUnitOfWorkFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUnitOfWorkFactory is an autogenerated mock type for the UnitOfWorkFactory type
type MockUnitOfWorkFactory struct {
	mock.Mock
}

type MockUnitOfWorkFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnitOfWorkFactory) EXPECT() *MockUnitOfWorkFactory_Expecter {
	return &MockUnitOfWorkFactory_Expecter{mock: &_m.Mock}
}

// NewUnitOfWork provides a mock function for the type MockUnitOfWorkFactory
func (_mock *MockUnitOfWorkFactory) NewUnitOfWork(ctx context.Context) (repo.UnitOfWork, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NewUnitOfWork")
	}

	var r0 repo.UnitOfWork
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (repo.UnitOfWork, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) repo.UnitOfWork); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repo.UnitOfWork)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUnitOfWorkFactory_NewUnitOfWork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewUnitOfWork'
type MockUnitOfWorkFactory_NewUnitOfWork_Call struct {
	*mock.Call
}

// NewUnitOfWork is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUnitOfWorkFactory_Expecter) NewUnitOfWork(ctx interface{}) *MockUnitOfWorkFactory_NewUnitOfWork_Call {
	return &MockUnitOfWorkFactory_NewUnitOfWork_Call{Call: _e.mock.On("NewUnitOfWork", ctx)}
}

func (_c *MockUnitOfWorkFactory_NewUnitOfWork_Call) Run(run func(ctx context.Context)) *MockUnitOfWorkFactory_NewUnitOfWork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUnitOfWorkFactory_NewUnitOfWork_Call) Return(unitOfWork repo.UnitOfWork, err error) *MockUnitOfWorkFactory_NewUnitOfWork_Call {
	_c.Call.Return(unitOfWork, err)
	return _c
}

func (_c *MockUnitOfWorkFactory_NewUnitOfWork_Call) RunAndReturn(run func(ctx context.Context) (repo.UnitOfWork, error)) *MockUnitOfWorkFactory_NewUnitOfWork_Call {
	_c.Call.Return(run)
	return _c
}
