// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repo

import (
	"context"

	"github.com/st-ember/streaming-api/internal/domain/video"
	mock "github.com/stretchr/testify/mock"
)

// NewMockVideoRepo creates a new instance of MockVideoRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVideoRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVideoRepo {
	mock := &MockVideoRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVideoRepo is an autogenerated mock type for the VideoRepo type
type MockVideoRepo struct {
	mock.Mock
}

type MockVideoRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVideoRepo) EXPECT() *MockVideoRepo_Expecter {
	return &MockVideoRepo_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type MockVideoRepo
func (_mock *MockVideoRepo) FindByID(ctx context.Context, id string) (*video.Video, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *video.Video
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*video.Video, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *video.Video); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*video.Video)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVideoRepo_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockVideoRepo_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockVideoRepo_Expecter) FindByID(ctx interface{}, id interface{}) *MockVideoRepo_FindByID_Call {
	return &MockVideoRepo_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockVideoRepo_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockVideoRepo_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVideoRepo_FindByID_Call) Return(video1 *video.Video, err error) *MockVideoRepo_FindByID_Call {
	_c.Call.Return(video1, err)
	return _c
}

func (_c *MockVideoRepo_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*video.Video, error)) *MockVideoRepo_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockVideoRepo
func (_mock *MockVideoRepo) Save(ctx context.Context, video1 *video.Video) error {
	ret := _mock.Called(ctx, video1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *video.Video) error); ok {
		r0 = returnFunc(ctx, video1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVideoRepo_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockVideoRepo_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - video1 *video.Video
func (_e *MockVideoRepo_Expecter) Save(ctx interface{}, video1 interface{}) *MockVideoRepo_Save_Call {
	return &MockVideoRepo_Save_Call{Call: _e.mock.On("Save", ctx, video1)}
}

func (_c *MockVideoRepo_Save_Call) Run(run func(ctx context.Context, video1 *video.Video)) *MockVideoRepo_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *video.Video
		if args[1] != nil {
			arg1 = args[1].(*video.Video)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVideoRepo_Save_Call) Return(err error) *MockVideoRepo_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVideoRepo_Save_Call) RunAndReturn(run func(ctx context.Context, video1 *video.Video) error) *MockVideoRepo_Save_Call {
	_c.Call.Return(run)
	return _c
}
