// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package storage

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAssetStorer creates a new instance of MockAssetStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAssetStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAssetStorer {
	mock := &MockAssetStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAssetStorer is an autogenerated mock type for the AssetStorer type
type MockAssetStorer struct {
	mock.Mock
}

type MockAssetStorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAssetStorer) EXPECT() *MockAssetStorer_Expecter {
	return &MockAssetStorer_Expecter{mock: &_m.Mock}
}

// DeleteAll provides a mock function for the type MockAssetStorer
func (_mock *MockAssetStorer) DeleteAll(ctx context.Context, resourceID string) error {
	ret := _mock.Called(ctx, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, resourceID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAssetStorer_DeleteAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAll'
type MockAssetStorer_DeleteAll_Call struct {
	*mock.Call
}

// DeleteAll is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceID string
func (_e *MockAssetStorer_Expecter) DeleteAll(ctx interface{}, resourceID interface{}) *MockAssetStorer_DeleteAll_Call {
	return &MockAssetStorer_DeleteAll_Call{Call: _e.mock.On("DeleteAll", ctx, resourceID)}
}

func (_c *MockAssetStorer_DeleteAll_Call) Run(run func(ctx context.Context, resourceID string)) *MockAssetStorer_DeleteAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAssetStorer_DeleteAll_Call) Return(err error) *MockAssetStorer_DeleteAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAssetStorer_DeleteAll_Call) RunAndReturn(run func(ctx context.Context, resourceID string) error) *MockAssetStorer_DeleteAll_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockAssetStorer
func (_mock *MockAssetStorer) Save(ctx context.Context, resourceID string, assetPath string, content io.Reader) error {
	ret := _mock.Called(ctx, resourceID, assetPath, content)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, io.Reader) error); ok {
		r0 = returnFunc(ctx, resourceID, assetPath, content)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAssetStorer_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockAssetStorer_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceID string
//   - assetPath string
//   - content io.Reader
func (_e *MockAssetStorer_Expecter) Save(ctx interface{}, resourceID interface{}, assetPath interface{}, content interface{}) *MockAssetStorer_Save_Call {
	return &MockAssetStorer_Save_Call{Call: _e.mock.On("Save", ctx, resourceID, assetPath, content)}
}

func (_c *MockAssetStorer_Save_Call) Run(run func(ctx context.Context, resourceID string, assetPath string, content io.Reader)) *MockAssetStorer_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 io.Reader
		if args[3] != nil {
			arg3 = args[3].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAssetStorer_Save_Call) Return(err error) *MockAssetStorer_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAssetStorer_Save_Call) RunAndReturn(run func(ctx context.Context, resourceID string, assetPath string, content io.Reader) error) *MockAssetStorer_Save_Call {
	_c.Call.Return(run)
	return _c
}
