// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package videoapp

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockArchiveVideoUsecase creates a new instance of MockArchiveVideoUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArchiveVideoUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArchiveVideoUsecase {
	mock := &MockArchiveVideoUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockArchiveVideoUsecase is an autogenerated mock type for the ArchiveVideoUsecase type
type MockArchiveVideoUsecase struct {
	mock.Mock
}

type MockArchiveVideoUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArchiveVideoUsecase) EXPECT() *MockArchiveVideoUsecase_Expecter {
	return &MockArchiveVideoUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockArchiveVideoUsecase
func (_mock *MockArchiveVideoUsecase) Execute(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockArchiveVideoUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockArchiveVideoUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockArchiveVideoUsecase_Expecter) Execute(ctx interface{}, id interface{}) *MockArchiveVideoUsecase_Execute_Call {
	return &MockArchiveVideoUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, id)}
}

func (_c *MockArchiveVideoUsecase_Execute_Call) Run(run func(ctx context.Context, id string)) *MockArchiveVideoUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockArchiveVideoUsecase_Execute_Call) Return(err error) *MockArchiveVideoUsecase_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockArchiveVideoUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockArchiveVideoUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
