// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package videoapp

import (
	"context"

	"github.com/st-ember/streaming-api/internal/application/videoapp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGetVideoInfoUsecase creates a new instance of MockGetVideoInfoUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetVideoInfoUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetVideoInfoUsecase {
	mock := &MockGetVideoInfoUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGetVideoInfoUsecase is an autogenerated mock type for the GetVideoInfoUsecase type
type MockGetVideoInfoUsecase struct {
	mock.Mock
}

type MockGetVideoInfoUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetVideoInfoUsecase) EXPECT() *MockGetVideoInfoUsecase_Expecter {
	return &MockGetVideoInfoUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockGetVideoInfoUsecase
func (_mock *MockGetVideoInfoUsecase) Execute(ctx context.Context, id string) (*videoapp.GetVideoInfoResult, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *videoapp.GetVideoInfoResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*videoapp.GetVideoInfoResult, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *videoapp.GetVideoInfoResult); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*videoapp.GetVideoInfoResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetVideoInfoUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGetVideoInfoUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockGetVideoInfoUsecase_Expecter) Execute(ctx interface{}, id interface{}) *MockGetVideoInfoUsecase_Execute_Call {
	return &MockGetVideoInfoUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, id)}
}

func (_c *MockGetVideoInfoUsecase_Execute_Call) Run(run func(ctx context.Context, id string)) *MockGetVideoInfoUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGetVideoInfoUsecase_Execute_Call) Return(getVideoInfoResult *videoapp.GetVideoInfoResult, err error) *MockGetVideoInfoUsecase_Execute_Call {
	_c.Call.Return(getVideoInfoResult, err)
	return _c
}

func (_c *MockGetVideoInfoUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, id string) (*videoapp.GetVideoInfoResult, error)) *MockGetVideoInfoUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
