// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package videoapp

import (
	"context"

	"github.com/st-ember/streaming-api/internal/domain/video"
	mock "github.com/stretchr/testify/mock"
)

// NewMockListVideosUsecase creates a new instance of MockListVideosUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListVideosUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListVideosUsecase {
	mock := &MockListVideosUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockListVideosUsecase is an autogenerated mock type for the ListVideosUsecase type
type MockListVideosUsecase struct {
	mock.Mock
}

type MockListVideosUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListVideosUsecase) EXPECT() *MockListVideosUsecase_Expecter {
	return &MockListVideosUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockListVideosUsecase
func (_mock *MockListVideosUsecase) Execute(ctx context.Context, page int) ([]*video.Video, error) {
	ret := _mock.Called(ctx, page)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []*video.Video
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*video.Video, error)); ok {
		return returnFunc(ctx, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*video.Video); ok {
		r0 = returnFunc(ctx, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*video.Video)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockListVideosUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockListVideosUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
func (_e *MockListVideosUsecase_Expecter) Execute(ctx interface{}, page interface{}) *MockListVideosUsecase_Execute_Call {
	return &MockListVideosUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, page)}
}

func (_c *MockListVideosUsecase_Execute_Call) Run(run func(ctx context.Context, page int)) *MockListVideosUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockListVideosUsecase_Execute_Call) Return(videos []*video.Video, err error) *MockListVideosUsecase_Execute_Call {
	_c.Call.Return(videos, err)
	return _c
}

func (_c *MockListVideosUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, page int) ([]*video.Video, error)) *MockListVideosUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
